### ISSUE TITLE
Trip duration should read only in hours, not days

### ISSUE THREAD

**Issue by anorthall** [anorthall/caves.app#95]
Trip duration strings should be limited to hours. For example, `25 hours`, not `1 day 1 hour`.

**Comment by priya1011** [comment]
@anorthall I would like to take on this issue, I will create a pull request with the changes once I have completed the implementation. Looking forward to contributing to the project!

**Comment by anorthall** [comment]
> @anorthall I would like to take on this issue, I will create a pull request with the changes once I have completed the implementation. Looking forward to contributing to the project!

Thanks @priya1011, let me know if you need any help.

**Comment by priya1011** [comment]
Could you please assign this to me?

**Comment by anorthall** [comment]
> Could you please assign this to me?

Done :)

**Comment by priya1011** [comment]
I have suppressed days, months and years and it will convert them to hours.
